biberltd_core_file_management_manage:
    pattern:  files/{sortcolumn}/{sortorder}/{file_number}
    defaults: { _controller: BiberLtdCoreBundlesContentManagementBundle:Manage:fileList }
    pattern:  files/edit/{file_id_or_code}
    defaults: { _controller: BiberLtdCoreBundlesContentManagementBundle:Manage:fileEdit }
    pattern:  files/new
    defaults: { _controller: BiberLtdCoreBundlesContentManagementBundle:Manage:fileNew }
    pattern:  files/delete
    defaults: { _controller: BiberLtdCoreBundlesContentManagementBundle:Manage:fileDelete }
    pattern:  files/upload
    defaults: { _controller: BiberLtdCoreBundlesContentManagementBundle:Manage:fileUpload}
    