services:
    filemanagement.model:
        class:        BiberLtd\Core\Bundles\FileManagementBundle\Services\FileManagementModel
        arguments:    [@kernel, "default", "doctrine"]
    filemanagement_fileupload.model:
        class:        BiberLtd\Core\Bundles\FileManagementBundle\Services\FileUpload
    filemanagement_imageupload.model:
        class:        BiberLtd\Core\Bundles\FileManagementBundle\Services\ImageUpload
    filemanagement_imagecrop.model:
        class:        BiberLtd\Core\Bundles\FileManagementBundle\Services\ImageCrop